version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "5000:5000"

volumes:
  jenkins_home:
    driver: local
